---
- name: Install dev packages
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - createrepo_c
      - freetype-devel
      - gcc
      - git
      - graphviz
      - koji
      - liberation-mono-fonts
      - libffi-devel
      - libjpeg-devel
      - libjpeg-turbo-devel
      - openssl-devel
      - pcaro-hermit-fonts
      - postgresql-devel
      - python
      - python-alembic
      - python-cornice
      - python-devel
      - python-librepo
      - python-mock
      - python-nose
      - python-pillow
      - python-psycopg2
      - python-webob
      - python-webtest
      - python-zmq
      - python-zope-sqlalchemy
      - python2-createrepo_c
      # We can switch this back to python2-fedmsg-atomic-composer once
      # https://bodhi.fedoraproject.org/updates/FEDORA-2016-bf2a514f37 is stable.
      - https://kojipkgs.fedoraproject.org//packages/python-fedmsg-atomic-composer/2016.3/1.fc25/noarch/python2-fedmsg-atomic-composer-2016.3-1.fc25.noarch.rpm
      - python2-fedmsg-consumers
      - python2-flake8
      - python2-nose-cov
      # We can switch this to python2-sqlalchemy_schemadisplay once
      # https://bodhi.fedoraproject.org/updates/FEDORA-2017-e54acedb77 is stable
      - https://kojipkgs.fedoraproject.org//packages/python-sqlalchemy_schemadisplay/1.3/1.fc24/noarch/python2-sqlalchemy_schemadisplay-1.3-1.fc24.noarch.rpm
      - redhat-rpm-config
      - zlib-devel

- name: Install bodhi in developer mode
  command: python /home/vagrant/bodhi/setup.py develop
  args:
      chdir: /home/vagrant/bodhi
      creates: /usr/lib/python2.7/site-packages/bodhi.egg-link

- name: Retrieve database dump
  get_url:
      url: https://infrastructure.fedoraproject.org/infra/db-dumps/bodhi2.dump.xz
      dest: /tmp/bodhi2.dump.xz

- shell: xzcat /tmp/bodhi2.dump.xz | runuser -l postgres -c 'psql bodhi2' && touch /home/vagrant/.db-imported
  args:
      creates: /home/vagrant/.db-imported

- command: cp /home/vagrant/bodhi/development.ini.example /home/vagrant/bodhi/development.ini
  args:
      creates: /home/vagrant/bodhi/development.ini

- name: Switch the database connection to postgres
  replace:
    dest: /home/vagrant/bodhi/development.ini
    regexp: "^sqlalchemy.url = sqlite.*$"
    replace: "sqlalchemy.url = postgresql://postgres:anypasswordworkslocally@localhost/bodhi2"

- name: Apply database migrations
  command: alembic upgrade head
  args:
      chdir: /home/vagrant/bodhi
